define(["big.js"], (__WEBPACK_EXTERNAL_MODULE_big_js__) => { return /******/ (() => { // webpackBootstrap
/******/ 	var __webpack_modules__ = ({

/***/ "E:\\quizapp-mx-course-master\\javascriptsource\\builder\\actions\\JS_Fix_OnQuestionBodyChange.js":
/*!***************************************************************************************************!*\
  !*** E:\quizapp-mx-course-master\javascriptsource\builder\actions\JS_Fix_OnQuestionBodyChange.js ***!
  \***************************************************************************************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   JS_Fix_OnQuestionBodyChange: () => (/* binding */ JS_Fix_OnQuestionBodyChange)
/* harmony export */ });
/* harmony import */ var mx_global__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! mx-global */ "?391f");
/* harmony import */ var mx_global__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(mx_global__WEBPACK_IMPORTED_MODULE_0__);
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! big.js */ "big.js");
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(big_js__WEBPACK_IMPORTED_MODULE_1__);
// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.



// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {MxObject} question
 * @returns {Promise.<void>}
 */
async function JS_Fix_OnQuestionBodyChange(question) {
  // BEGIN USER CODE

  function isWrapped(strHTML) {
    return strHTML.startsWith("<p>") && strHTML.endsWith("</p>");
  }
  function wrap(strHTML) {
    return "<p>" + strHTML + "</p>";
  }
  function placeCaretAtEnd(el) {
    el.focus();
    if (typeof window.getSelection != "undefined" && typeof document.createRange != "undefined") {
      const range = document.createRange();
      range.selectNodeContents(el);
      range.collapse(false);
      const sel = window.getSelection();
      sel.removeAllRanges();
      sel.addRange(range);
    } else if (typeof document.body.createTextRange != "undefined") {
      const textRange = document.body.createTextRange();
      textRange.moveToElementText(el);
      textRange.collapse(false);
      textRange.select();
    }
  }
  const questionBody = question.get("QuestionBody");
  const textEditor = document.getElementsByClassName("w-e-text")[0];
  const wrapped = isWrapped(questionBody);
  if (wrapped) {
    return;
  }
  textEditor.innerHTML = wrap(questionBody);
  placeCaretAtEnd(textEditor);

  // END USER CODE
}

/***/ }),

/***/ "E:\\quizapp-mx-course-master\\javascriptsource\\builder\\actions\\JS_Fix_OnQuestionChange.js":
/*!***********************************************************************************************!*\
  !*** E:\quizapp-mx-course-master\javascriptsource\builder\actions\JS_Fix_OnQuestionChange.js ***!
  \***********************************************************************************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   JS_Fix_OnQuestionChange: () => (/* binding */ JS_Fix_OnQuestionChange)
/* harmony export */ });
/* harmony import */ var mx_global__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! mx-global */ "?391f");
/* harmony import */ var mx_global__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(mx_global__WEBPACK_IMPORTED_MODULE_0__);
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! big.js */ "big.js");
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(big_js__WEBPACK_IMPORTED_MODULE_1__);
// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.



// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {MxObject} question
 * @returns {Promise.<void>}
 */
async function JS_Fix_OnQuestionChange(question) {
  // BEGIN USER CODE

  function isWrapped(strHTML) {
    return strHTML.startsWith("<p>") && strHTML.endsWith("</p>");
  }
  function wrap(strHTML) {
    return "<p>" + strHTML + "</p>";
  }
  const questionBody = question.get("QuestionBody");
  const textEditor = document.getElementsByClassName("w-e-text")[0];
  const wrapped = isWrapped(questionBody);
  if (wrapped) {
    return textEditor.innerHTML = questionBody;
  }
  textEditor.innerHTML = wrap(questionBody);

  // END USER CODE
}

/***/ }),

/***/ "E:\\quizapp-mx-course-master\\javascriptsource\\nanoflowcommons\\actions\\HideProgress.js":
/*!********************************************************************************************!*\
  !*** E:\quizapp-mx-course-master\javascriptsource\nanoflowcommons\actions\HideProgress.js ***!
  \********************************************************************************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   HideProgress: () => (/* binding */ HideProgress)
/* harmony export */ });
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! big.js */ "big.js");
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(big_js__WEBPACK_IMPORTED_MODULE_0__);
// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.


// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * Hides default progress bar
 * @param {Big} identifier - Identifier of ui which should be hidden. This param is required
 * @returns {Promise.<void>}
 */
async function HideProgress(identifier) {
  // BEGIN USER CODE
  if (identifier == null) {
    return Promise.reject(new Error("Input parameter 'Identifier' is required"));
  }
  mx.ui.hideProgress(Number(identifier));
  return Promise.resolve();
  // END USER CODE
}

/***/ }),

/***/ "E:\\quizapp-mx-course-master\\javascriptsource\\nanoflowcommons\\actions\\ShowProgress.js":
/*!********************************************************************************************!*\
  !*** E:\quizapp-mx-course-master\javascriptsource\nanoflowcommons\actions\ShowProgress.js ***!
  \********************************************************************************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   ShowProgress: () => (/* binding */ ShowProgress)
/* harmony export */ });
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! big.js */ "big.js");
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(big_js__WEBPACK_IMPORTED_MODULE_0__);
// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.


// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * Shows default progress bar
 * @param {string} message - The text to show while loading.
 * @param {boolean} blocking - Block the user interface immediately.
 * @returns {Promise.<Big>}
 */
async function ShowProgress(message, blocking) {
  // BEGIN USER CODE
  const id = mx.ui.showProgress(message, blocking);
  if (id !== undefined) {
    return Promise.resolve(new big_js__WEBPACK_IMPORTED_MODULE_0__.Big(id));
  }
  return Promise.reject(new Error("Could not open the loading dialog"));
  // END USER CODE
}

/***/ }),

/***/ "big.js":
/*!*************************!*\
  !*** external "big.js" ***!
  \*************************/
/***/ ((module) => {

"use strict";
module.exports = __WEBPACK_EXTERNAL_MODULE_big_js__;

/***/ }),

/***/ "?391f":
/*!**********************************!*\
  !*** mx-global (ignored module) ***!
  \**********************************/
/***/ (() => {

/* empty */

/***/ })

/******/ 	});
/************************************************************************/
/******/ 	// The module cache
/******/ 	var __webpack_module_cache__ = {};
/******/ 	
/******/ 	// The require function
/******/ 	function __webpack_require__(moduleId) {
/******/ 		// Check if module is in cache
/******/ 		var cachedModule = __webpack_module_cache__[moduleId];
/******/ 		if (cachedModule !== undefined) {
/******/ 			return cachedModule.exports;
/******/ 		}
/******/ 		// Create a new module (and put it into the cache)
/******/ 		var module = __webpack_module_cache__[moduleId] = {
/******/ 			// no module.id needed
/******/ 			// no module.loaded needed
/******/ 			exports: {}
/******/ 		};
/******/ 	
/******/ 		// Execute the module function
/******/ 		__webpack_modules__[moduleId](module, module.exports, __webpack_require__);
/******/ 	
/******/ 		// Return the exports of the module
/******/ 		return module.exports;
/******/ 	}
/******/ 	
/************************************************************************/
/******/ 	/* webpack/runtime/compat get default export */
/******/ 	(() => {
/******/ 		// getDefaultExport function for compatibility with non-harmony modules
/******/ 		__webpack_require__.n = (module) => {
/******/ 			var getter = module && module.__esModule ?
/******/ 				() => (module['default']) :
/******/ 				() => (module);
/******/ 			__webpack_require__.d(getter, { a: getter });
/******/ 			return getter;
/******/ 		};
/******/ 	})();
/******/ 	
/******/ 	/* webpack/runtime/define property getters */
/******/ 	(() => {
/******/ 		// define getter functions for harmony exports
/******/ 		__webpack_require__.d = (exports, definition) => {
/******/ 			for(var key in definition) {
/******/ 				if(__webpack_require__.o(definition, key) && !__webpack_require__.o(exports, key)) {
/******/ 					Object.defineProperty(exports, key, { enumerable: true, get: definition[key] });
/******/ 				}
/******/ 			}
/******/ 		};
/******/ 	})();
/******/ 	
/******/ 	/* webpack/runtime/hasOwnProperty shorthand */
/******/ 	(() => {
/******/ 		__webpack_require__.o = (obj, prop) => (Object.prototype.hasOwnProperty.call(obj, prop))
/******/ 	})();
/******/ 	
/******/ 	/* webpack/runtime/make namespace object */
/******/ 	(() => {
/******/ 		// define __esModule on exports
/******/ 		__webpack_require__.r = (exports) => {
/******/ 			if(typeof Symbol !== 'undefined' && Symbol.toStringTag) {
/******/ 				Object.defineProperty(exports, Symbol.toStringTag, { value: 'Module' });
/******/ 			}
/******/ 			Object.defineProperty(exports, '__esModule', { value: true });
/******/ 		};
/******/ 	})();
/******/ 	
/************************************************************************/
var __webpack_exports__ = {};
// This entry need to be wrapped in an IIFE because it need to be in strict mode.
(() => {
"use strict";
/*!***************************************************************!*\
  !*** E:\quizapp-mx-course-master\deployment\tmp\jsactions.js ***!
  \***************************************************************/
__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   Builder$JS_Fix_OnQuestionBodyChange: () => (/* binding */ Builder$JS_Fix_OnQuestionBodyChange),
/* harmony export */   Builder$JS_Fix_OnQuestionChange: () => (/* binding */ Builder$JS_Fix_OnQuestionChange),
/* harmony export */   NanoflowCommons$HideProgress: () => (/* binding */ NanoflowCommons$HideProgress),
/* harmony export */   NanoflowCommons$ShowProgress: () => (/* binding */ NanoflowCommons$ShowProgress)
/* harmony export */ });
const NanoflowCommons$ShowProgress = async () => (await Promise.resolve(/*! import() */).then(__webpack_require__.bind(__webpack_require__, /*! E:\quizapp-mx-course-master\javascriptsource\nanoflowcommons\actions\ShowProgress */ "E:\\quizapp-mx-course-master\\javascriptsource\\nanoflowcommons\\actions\\ShowProgress.js"))).ShowProgress;
const NanoflowCommons$HideProgress = async () => (await Promise.resolve(/*! import() */).then(__webpack_require__.bind(__webpack_require__, /*! E:\quizapp-mx-course-master\javascriptsource\nanoflowcommons\actions\HideProgress */ "E:\\quizapp-mx-course-master\\javascriptsource\\nanoflowcommons\\actions\\HideProgress.js"))).HideProgress;
const Builder$JS_Fix_OnQuestionChange = async () => (await Promise.resolve(/*! import() */).then(__webpack_require__.bind(__webpack_require__, /*! E:\quizapp-mx-course-master\javascriptsource\builder\actions\JS_Fix_OnQuestionChange */ "E:\\quizapp-mx-course-master\\javascriptsource\\builder\\actions\\JS_Fix_OnQuestionChange.js"))).JS_Fix_OnQuestionChange;
const Builder$JS_Fix_OnQuestionBodyChange = async () => (await Promise.resolve(/*! import() */).then(__webpack_require__.bind(__webpack_require__, /*! E:\quizapp-mx-course-master\javascriptsource\builder\actions\JS_Fix_OnQuestionBodyChange */ "E:\\quizapp-mx-course-master\\javascriptsource\\builder\\actions\\JS_Fix_OnQuestionBodyChange.js"))).JS_Fix_OnQuestionBodyChange;
})();

/******/ 	return __webpack_exports__;
/******/ })()
;
});;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoianNhY3Rpb25zLmpzIiwibWFwcGluZ3MiOiI7Ozs7Ozs7Ozs7Ozs7Ozs7OztBQUFBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ21CO0FBQ1U7O0FBRTdCO0FBQ0E7O0FBRUE7QUFDQTtBQUNBO0FBQ0E7QUFDTyxlQUFlQywyQkFBMkIsQ0FBQ0MsUUFBUSxFQUFFO0VBQzNEOztFQUVBLFNBQVNDLFNBQVMsQ0FBQ0MsT0FBTyxFQUFFO0lBQzNCLE9BQU9BLE9BQU8sQ0FBQ0MsVUFBVSxDQUFDLEtBQUssQ0FBQyxJQUFJRCxPQUFPLENBQUNFLFFBQVEsQ0FBQyxNQUFNLENBQUM7RUFFN0Q7RUFDQSxTQUFTQyxJQUFJLENBQUNILE9BQU8sRUFBRTtJQUN0QixPQUFPLEtBQUssR0FBR0EsT0FBTyxHQUFHLE1BQU07RUFDaEM7RUFFQSxTQUFTSSxlQUFlLENBQUNDLEVBQUUsRUFBRTtJQUM1QkEsRUFBRSxDQUFDQyxLQUFLLEVBQUU7SUFDVixJQUFJLE9BQU9DLE1BQU0sQ0FBQ0MsWUFBWSxJQUFJLFdBQVcsSUFBSSxPQUFPQyxRQUFRLENBQUNDLFdBQVcsSUFBSSxXQUFXLEVBQUU7TUFDNUYsTUFBTUMsS0FBSyxHQUFHRixRQUFRLENBQUNDLFdBQVcsRUFBRTtNQUNwQ0MsS0FBSyxDQUFDQyxrQkFBa0IsQ0FBQ1AsRUFBRSxDQUFDO01BQzVCTSxLQUFLLENBQUNFLFFBQVEsQ0FBQyxLQUFLLENBQUM7TUFDckIsTUFBTUMsR0FBRyxHQUFHUCxNQUFNLENBQUNDLFlBQVksRUFBRTtNQUNqQ00sR0FBRyxDQUFDQyxlQUFlLEVBQUU7TUFDckJELEdBQUcsQ0FBQ0UsUUFBUSxDQUFDTCxLQUFLLENBQUM7SUFDcEIsQ0FBQyxNQUFNLElBQUksT0FBT0YsUUFBUSxDQUFDUSxJQUFJLENBQUNDLGVBQWUsSUFBSSxXQUFXLEVBQUU7TUFDL0QsTUFBTUMsU0FBUyxHQUFHVixRQUFRLENBQUNRLElBQUksQ0FBQ0MsZUFBZSxFQUFFO01BQ2pEQyxTQUFTLENBQUNDLGlCQUFpQixDQUFDZixFQUFFLENBQUM7TUFDL0JjLFNBQVMsQ0FBQ04sUUFBUSxDQUFDLEtBQUssQ0FBQztNQUN6Qk0sU0FBUyxDQUFDRSxNQUFNLEVBQUU7SUFDbkI7RUFDRDtFQUVBLE1BQU1DLFlBQVksR0FBR3hCLFFBQVEsQ0FBQ3lCLEdBQUcsQ0FBQyxjQUFjLENBQUM7RUFDakQsTUFBTUMsVUFBVSxHQUFHZixRQUFRLENBQUNnQixzQkFBc0IsQ0FBQyxVQUFVLENBQUMsQ0FBQyxDQUFDLENBQUM7RUFDakUsTUFBTUMsT0FBTyxHQUFHM0IsU0FBUyxDQUFDdUIsWUFBWSxDQUFDO0VBRXZDLElBQUlJLE9BQU8sRUFBRTtJQUNaO0VBQ0Q7RUFFQUYsVUFBVSxDQUFDRyxTQUFTLEdBQUd4QixJQUFJLENBQUNtQixZQUFZLENBQUM7RUFDekNsQixlQUFlLENBQUNvQixVQUFVLENBQUM7O0VBRTNCO0FBQ0Q7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7QUN6REE7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDbUI7QUFDVTs7QUFFN0I7QUFDQTs7QUFFQTtBQUNBO0FBQ0E7QUFDQTtBQUNPLGVBQWVJLHVCQUF1QixDQUFDOUIsUUFBUSxFQUFFO0VBQ3ZEOztFQUVBLFNBQVNDLFNBQVMsQ0FBQ0MsT0FBTyxFQUFFO0lBQzNCLE9BQU9BLE9BQU8sQ0FBQ0MsVUFBVSxDQUFDLEtBQUssQ0FBQyxJQUFJRCxPQUFPLENBQUNFLFFBQVEsQ0FBQyxNQUFNLENBQUM7RUFFN0Q7RUFFQSxTQUFTQyxJQUFJLENBQUNILE9BQU8sRUFBRTtJQUN0QixPQUFPLEtBQUssR0FBR0EsT0FBTyxHQUFHLE1BQU07RUFDaEM7RUFFQSxNQUFNc0IsWUFBWSxHQUFHeEIsUUFBUSxDQUFDeUIsR0FBRyxDQUFDLGNBQWMsQ0FBQztFQUNqRCxNQUFNQyxVQUFVLEdBQUdmLFFBQVEsQ0FBQ2dCLHNCQUFzQixDQUFDLFVBQVUsQ0FBQyxDQUFDLENBQUMsQ0FBQztFQUNqRSxNQUFNQyxPQUFPLEdBQUczQixTQUFTLENBQUN1QixZQUFZLENBQUM7RUFFdkMsSUFBSUksT0FBTyxFQUFFO0lBQ1osT0FBT0YsVUFBVSxDQUFDRyxTQUFTLEdBQUdMLFlBQVk7RUFDM0M7RUFHQUUsVUFBVSxDQUFDRyxTQUFTLEdBQUd4QixJQUFJLENBQUNtQixZQUFZLENBQUM7O0VBRXpDO0FBQ0Q7Ozs7Ozs7Ozs7Ozs7Ozs7O0FDekNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQzZCOztBQUU3QjtBQUNBOztBQUVBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDTyxlQUFlTyxZQUFZLENBQUNDLFVBQVUsRUFBRTtFQUM5QztFQUNHLElBQUlBLFVBQVUsSUFBSSxJQUFJLEVBQUU7SUFDcEIsT0FBT0MsT0FBTyxDQUFDQyxNQUFNLENBQUMsSUFBSUMsS0FBSyxDQUFDLDBDQUEwQyxDQUFDLENBQUM7RUFDaEY7RUFDQUMsRUFBRSxDQUFDQyxFQUFFLENBQUNDLFlBQVksQ0FBQ0MsTUFBTSxDQUFDUCxVQUFVLENBQUMsQ0FBQztFQUN0QyxPQUFPQyxPQUFPLENBQUNPLE9BQU8sRUFBRTtFQUMzQjtBQUNEOzs7Ozs7Ozs7Ozs7Ozs7OztBQ3pCQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUM2Qjs7QUFFN0I7QUFDQTs7QUFFQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDTyxlQUFlQyxZQUFZLENBQUNDLE9BQU8sRUFBRUMsUUFBUSxFQUFFO0VBQ3JEO0VBQ0csTUFBTUMsRUFBRSxHQUFHUixFQUFFLENBQUNDLEVBQUUsQ0FBQ1EsWUFBWSxDQUFDSCxPQUFPLEVBQUVDLFFBQVEsQ0FBQztFQUNoRCxJQUFJQyxFQUFFLEtBQUtFLFNBQVMsRUFBRTtJQUNsQixPQUFPYixPQUFPLENBQUNPLE9BQU8sQ0FBQyxJQUFJMUMsdUNBQUcsQ0FBQzhDLEVBQUUsQ0FBQyxDQUFDO0VBQ3ZDO0VBQ0EsT0FBT1gsT0FBTyxDQUFDQyxNQUFNLENBQUMsSUFBSUMsS0FBSyxDQUFDLG1DQUFtQyxDQUFDLENBQUM7RUFDeEU7QUFDRDs7Ozs7Ozs7Ozs7QUMxQkE7Ozs7Ozs7Ozs7QUNBQTs7Ozs7O1VDQUE7VUFDQTs7VUFFQTtVQUNBO1VBQ0E7VUFDQTtVQUNBO1VBQ0E7VUFDQTtVQUNBO1VBQ0E7VUFDQTtVQUNBO1VBQ0E7VUFDQTs7VUFFQTtVQUNBOztVQUVBO1VBQ0E7VUFDQTs7Ozs7V0N0QkE7V0FDQTtXQUNBO1dBQ0E7V0FDQTtXQUNBLGlDQUFpQyxXQUFXO1dBQzVDO1dBQ0E7Ozs7O1dDUEE7V0FDQTtXQUNBO1dBQ0E7V0FDQSx5Q0FBeUMsd0NBQXdDO1dBQ2pGO1dBQ0E7V0FDQTs7Ozs7V0NQQTs7Ozs7V0NBQTtXQUNBO1dBQ0E7V0FDQSx1REFBdUQsaUJBQWlCO1dBQ3hFO1dBQ0EsZ0RBQWdELGFBQWE7V0FDN0Q7Ozs7Ozs7Ozs7Ozs7Ozs7OztBQ05PLE1BQU1ZLDRCQUE0QixHQUFHLFlBQVksQ0FBQyxNQUFNLDBRQUEyRixFQUFFTixZQUFZO0FBQ2pLLE1BQU1PLDRCQUE0QixHQUFHLFlBQVksQ0FBQyxNQUFNLDBRQUEyRixFQUFFakIsWUFBWTtBQUNqSyxNQUFNa0IsK0JBQStCLEdBQUcsWUFBWSxDQUFDLE1BQU0sZ1JBQThGLEVBQUVuQix1QkFBdUI7QUFDbEwsTUFBTW9CLG1DQUFtQyxHQUFHLFlBQVksQ0FBQyxNQUFNLHdSQUFrRyxFQUFFbkQsMkJBQTJCLEMiLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vRTpcXHF1aXphcHAtbXgtY291cnNlLW1hc3RlclxcamF2YXNjcmlwdHNvdXJjZVxcYnVpbGRlclxcYWN0aW9uc1xcSlNfRml4X09uUXVlc3Rpb25Cb2R5Q2hhbmdlLmpzIiwid2VicGFjazovLy9FOlxccXVpemFwcC1teC1jb3Vyc2UtbWFzdGVyXFxqYXZhc2NyaXB0c291cmNlXFxidWlsZGVyXFxhY3Rpb25zXFxKU19GaXhfT25RdWVzdGlvbkNoYW5nZS5qcyIsIndlYnBhY2s6Ly8vRTpcXHF1aXphcHAtbXgtY291cnNlLW1hc3RlclxcamF2YXNjcmlwdHNvdXJjZVxcbmFub2Zsb3djb21tb25zXFxhY3Rpb25zXFxIaWRlUHJvZ3Jlc3MuanMiLCJ3ZWJwYWNrOi8vL0U6XFxxdWl6YXBwLW14LWNvdXJzZS1tYXN0ZXJcXGphdmFzY3JpcHRzb3VyY2VcXG5hbm9mbG93Y29tbW9uc1xcYWN0aW9uc1xcU2hvd1Byb2dyZXNzLmpzIiwid2VicGFjazovLy9leHRlcm5hbCBhbWQgXCJiaWcuanNcIiIsIndlYnBhY2s6Ly8vbXgtZ2xvYmFsIiwid2VicGFjazovLy93ZWJwYWNrL2Jvb3RzdHJhcCIsIndlYnBhY2s6Ly8vd2VicGFjay9ydW50aW1lL2NvbXBhdCBnZXQgZGVmYXVsdCBleHBvcnQiLCJ3ZWJwYWNrOi8vL3dlYnBhY2svcnVudGltZS9kZWZpbmUgcHJvcGVydHkgZ2V0dGVycyIsIndlYnBhY2s6Ly8vd2VicGFjay9ydW50aW1lL2hhc093blByb3BlcnR5IHNob3J0aGFuZCIsIndlYnBhY2s6Ly8vd2VicGFjay9ydW50aW1lL21ha2UgbmFtZXNwYWNlIG9iamVjdCIsIndlYnBhY2s6Ly8vRTpcXHF1aXphcHAtbXgtY291cnNlLW1hc3RlclxcZGVwbG95bWVudFxcdG1wXFxqc2FjdGlvbnMuanMiXSwic291cmNlc0NvbnRlbnQiOlsiLy8gVGhpcyBmaWxlIHdhcyBnZW5lcmF0ZWQgYnkgTWVuZGl4IFN0dWRpbyBQcm8uXHJcbi8vXHJcbi8vIFdBUk5JTkc6IE9ubHkgdGhlIGZvbGxvd2luZyBjb2RlIHdpbGwgYmUgcmV0YWluZWQgd2hlbiBhY3Rpb25zIGFyZSByZWdlbmVyYXRlZDpcclxuLy8gLSB0aGUgaW1wb3J0IGxpc3RcclxuLy8gLSB0aGUgY29kZSBiZXR3ZWVuIEJFR0lOIFVTRVIgQ09ERSBhbmQgRU5EIFVTRVIgQ09ERVxyXG4vLyAtIHRoZSBjb2RlIGJldHdlZW4gQkVHSU4gRVhUUkEgQ09ERSBhbmQgRU5EIEVYVFJBIENPREVcclxuLy8gT3RoZXIgY29kZSB5b3Ugd3JpdGUgd2lsbCBiZSBsb3N0IHRoZSBuZXh0IHRpbWUgeW91IGRlcGxveSB0aGUgcHJvamVjdC5cclxuaW1wb3J0IFwibXgtZ2xvYmFsXCI7XHJcbmltcG9ydCB7IEJpZyB9IGZyb20gXCJiaWcuanNcIjtcclxuXHJcbi8vIEJFR0lOIEVYVFJBIENPREVcclxuLy8gRU5EIEVYVFJBIENPREVcclxuXHJcbi8qKlxyXG4gKiBAcGFyYW0ge014T2JqZWN0fSBxdWVzdGlvblxyXG4gKiBAcmV0dXJucyB7UHJvbWlzZS48dm9pZD59XHJcbiAqL1xyXG5leHBvcnQgYXN5bmMgZnVuY3Rpb24gSlNfRml4X09uUXVlc3Rpb25Cb2R5Q2hhbmdlKHF1ZXN0aW9uKSB7XHJcblx0Ly8gQkVHSU4gVVNFUiBDT0RFXHJcblx0XHJcblx0ZnVuY3Rpb24gaXNXcmFwcGVkKHN0ckhUTUwpIHtcclxuXHRcdHJldHVybiBzdHJIVE1MLnN0YXJ0c1dpdGgoXCI8cD5cIikgJiYgc3RySFRNTC5lbmRzV2l0aChcIjwvcD5cIik7XHJcblxyXG5cdH1cclxuXHRmdW5jdGlvbiB3cmFwKHN0ckhUTUwpIHtcclxuXHRcdHJldHVybiBcIjxwPlwiICsgc3RySFRNTCArIFwiPC9wPlwiO1xyXG5cdH1cclxuXHJcblx0ZnVuY3Rpb24gcGxhY2VDYXJldEF0RW5kKGVsKSB7XHJcblx0XHRlbC5mb2N1cygpO1xyXG5cdFx0aWYgKHR5cGVvZiB3aW5kb3cuZ2V0U2VsZWN0aW9uICE9IFwidW5kZWZpbmVkXCIgJiYgdHlwZW9mIGRvY3VtZW50LmNyZWF0ZVJhbmdlICE9IFwidW5kZWZpbmVkXCIpIHtcclxuXHRcdFx0Y29uc3QgcmFuZ2UgPSBkb2N1bWVudC5jcmVhdGVSYW5nZSgpO1xyXG5cdFx0XHRyYW5nZS5zZWxlY3ROb2RlQ29udGVudHMoZWwpO1xyXG5cdFx0XHRyYW5nZS5jb2xsYXBzZShmYWxzZSk7XHJcblx0XHRcdGNvbnN0IHNlbCA9IHdpbmRvdy5nZXRTZWxlY3Rpb24oKTtcclxuXHRcdFx0c2VsLnJlbW92ZUFsbFJhbmdlcygpO1xyXG5cdFx0XHRzZWwuYWRkUmFuZ2UocmFuZ2UpO1xyXG5cdFx0fSBlbHNlIGlmICh0eXBlb2YgZG9jdW1lbnQuYm9keS5jcmVhdGVUZXh0UmFuZ2UgIT0gXCJ1bmRlZmluZWRcIikge1xyXG5cdFx0XHRjb25zdCB0ZXh0UmFuZ2UgPSBkb2N1bWVudC5ib2R5LmNyZWF0ZVRleHRSYW5nZSgpO1xyXG5cdFx0XHR0ZXh0UmFuZ2UubW92ZVRvRWxlbWVudFRleHQoZWwpO1xyXG5cdFx0XHR0ZXh0UmFuZ2UuY29sbGFwc2UoZmFsc2UpO1xyXG5cdFx0XHR0ZXh0UmFuZ2Uuc2VsZWN0KCk7XHJcblx0XHR9XHJcblx0fVxyXG5cclxuXHRjb25zdCBxdWVzdGlvbkJvZHkgPSBxdWVzdGlvbi5nZXQoXCJRdWVzdGlvbkJvZHlcIik7XHJcblx0Y29uc3QgdGV4dEVkaXRvciA9IGRvY3VtZW50LmdldEVsZW1lbnRzQnlDbGFzc05hbWUoXCJ3LWUtdGV4dFwiKVswXTtcclxuXHRjb25zdCB3cmFwcGVkID0gaXNXcmFwcGVkKHF1ZXN0aW9uQm9keSk7XHJcblx0XHJcblx0aWYgKHdyYXBwZWQpIHtcclxuXHRcdHJldHVybjtcclxuXHR9XHJcblxyXG5cdHRleHRFZGl0b3IuaW5uZXJIVE1MID0gd3JhcChxdWVzdGlvbkJvZHkpO1xyXG5cdHBsYWNlQ2FyZXRBdEVuZCh0ZXh0RWRpdG9yKTtcclxuXHJcblx0Ly8gRU5EIFVTRVIgQ09ERVxyXG59XHJcbiIsIi8vIFRoaXMgZmlsZSB3YXMgZ2VuZXJhdGVkIGJ5IE1lbmRpeCBTdHVkaW8gUHJvLlxyXG4vL1xyXG4vLyBXQVJOSU5HOiBPbmx5IHRoZSBmb2xsb3dpbmcgY29kZSB3aWxsIGJlIHJldGFpbmVkIHdoZW4gYWN0aW9ucyBhcmUgcmVnZW5lcmF0ZWQ6XHJcbi8vIC0gdGhlIGltcG9ydCBsaXN0XHJcbi8vIC0gdGhlIGNvZGUgYmV0d2VlbiBCRUdJTiBVU0VSIENPREUgYW5kIEVORCBVU0VSIENPREVcclxuLy8gLSB0aGUgY29kZSBiZXR3ZWVuIEJFR0lOIEVYVFJBIENPREUgYW5kIEVORCBFWFRSQSBDT0RFXHJcbi8vIE90aGVyIGNvZGUgeW91IHdyaXRlIHdpbGwgYmUgbG9zdCB0aGUgbmV4dCB0aW1lIHlvdSBkZXBsb3kgdGhlIHByb2plY3QuXHJcbmltcG9ydCBcIm14LWdsb2JhbFwiO1xyXG5pbXBvcnQgeyBCaWcgfSBmcm9tIFwiYmlnLmpzXCI7XHJcblxyXG4vLyBCRUdJTiBFWFRSQSBDT0RFXHJcbi8vIEVORCBFWFRSQSBDT0RFXHJcblxyXG4vKipcclxuICogQHBhcmFtIHtNeE9iamVjdH0gcXVlc3Rpb25cclxuICogQHJldHVybnMge1Byb21pc2UuPHZvaWQ+fVxyXG4gKi9cclxuZXhwb3J0IGFzeW5jIGZ1bmN0aW9uIEpTX0ZpeF9PblF1ZXN0aW9uQ2hhbmdlKHF1ZXN0aW9uKSB7XHJcblx0Ly8gQkVHSU4gVVNFUiBDT0RFXHJcblxyXG5cdGZ1bmN0aW9uIGlzV3JhcHBlZChzdHJIVE1MKSB7XHJcblx0XHRyZXR1cm4gc3RySFRNTC5zdGFydHNXaXRoKFwiPHA+XCIpICYmIHN0ckhUTUwuZW5kc1dpdGgoXCI8L3A+XCIpO1xyXG5cclxuXHR9XHJcblxyXG5cdGZ1bmN0aW9uIHdyYXAoc3RySFRNTCkge1xyXG5cdFx0cmV0dXJuIFwiPHA+XCIgKyBzdHJIVE1MICsgXCI8L3A+XCI7XHJcblx0fVxyXG5cclxuXHRjb25zdCBxdWVzdGlvbkJvZHkgPSBxdWVzdGlvbi5nZXQoXCJRdWVzdGlvbkJvZHlcIik7XHJcblx0Y29uc3QgdGV4dEVkaXRvciA9IGRvY3VtZW50LmdldEVsZW1lbnRzQnlDbGFzc05hbWUoXCJ3LWUtdGV4dFwiKVswXTtcclxuXHRjb25zdCB3cmFwcGVkID0gaXNXcmFwcGVkKHF1ZXN0aW9uQm9keSk7XHJcblxyXG5cdGlmICh3cmFwcGVkKSB7XHJcblx0XHRyZXR1cm4gdGV4dEVkaXRvci5pbm5lckhUTUwgPSBxdWVzdGlvbkJvZHk7XHJcblx0fVxyXG5cclxuXHJcblx0dGV4dEVkaXRvci5pbm5lckhUTUwgPSB3cmFwKHF1ZXN0aW9uQm9keSk7XHJcblxyXG5cdC8vIEVORCBVU0VSIENPREVcclxufVxyXG4iLCIvLyBUaGlzIGZpbGUgd2FzIGdlbmVyYXRlZCBieSBNZW5kaXggU3R1ZGlvIFByby5cclxuLy9cclxuLy8gV0FSTklORzogT25seSB0aGUgZm9sbG93aW5nIGNvZGUgd2lsbCBiZSByZXRhaW5lZCB3aGVuIGFjdGlvbnMgYXJlIHJlZ2VuZXJhdGVkOlxyXG4vLyAtIHRoZSBpbXBvcnQgbGlzdFxyXG4vLyAtIHRoZSBjb2RlIGJldHdlZW4gQkVHSU4gVVNFUiBDT0RFIGFuZCBFTkQgVVNFUiBDT0RFXHJcbi8vIC0gdGhlIGNvZGUgYmV0d2VlbiBCRUdJTiBFWFRSQSBDT0RFIGFuZCBFTkQgRVhUUkEgQ09ERVxyXG4vLyBPdGhlciBjb2RlIHlvdSB3cml0ZSB3aWxsIGJlIGxvc3QgdGhlIG5leHQgdGltZSB5b3UgZGVwbG95IHRoZSBwcm9qZWN0LlxyXG5pbXBvcnQgeyBCaWcgfSBmcm9tIFwiYmlnLmpzXCI7XHJcblxyXG4vLyBCRUdJTiBFWFRSQSBDT0RFXHJcbi8vIEVORCBFWFRSQSBDT0RFXHJcblxyXG4vKipcclxuICogSGlkZXMgZGVmYXVsdCBwcm9ncmVzcyBiYXJcclxuICogQHBhcmFtIHtCaWd9IGlkZW50aWZpZXIgLSBJZGVudGlmaWVyIG9mIHVpIHdoaWNoIHNob3VsZCBiZSBoaWRkZW4uIFRoaXMgcGFyYW0gaXMgcmVxdWlyZWRcclxuICogQHJldHVybnMge1Byb21pc2UuPHZvaWQ+fVxyXG4gKi9cclxuZXhwb3J0IGFzeW5jIGZ1bmN0aW9uIEhpZGVQcm9ncmVzcyhpZGVudGlmaWVyKSB7XHJcblx0Ly8gQkVHSU4gVVNFUiBDT0RFXHJcbiAgICBpZiAoaWRlbnRpZmllciA9PSBudWxsKSB7XHJcbiAgICAgICAgcmV0dXJuIFByb21pc2UucmVqZWN0KG5ldyBFcnJvcihcIklucHV0IHBhcmFtZXRlciAnSWRlbnRpZmllcicgaXMgcmVxdWlyZWRcIikpO1xyXG4gICAgfVxyXG4gICAgbXgudWkuaGlkZVByb2dyZXNzKE51bWJlcihpZGVudGlmaWVyKSk7XHJcbiAgICByZXR1cm4gUHJvbWlzZS5yZXNvbHZlKCk7XHJcblx0Ly8gRU5EIFVTRVIgQ09ERVxyXG59XHJcbiIsIi8vIFRoaXMgZmlsZSB3YXMgZ2VuZXJhdGVkIGJ5IE1lbmRpeCBTdHVkaW8gUHJvLlxyXG4vL1xyXG4vLyBXQVJOSU5HOiBPbmx5IHRoZSBmb2xsb3dpbmcgY29kZSB3aWxsIGJlIHJldGFpbmVkIHdoZW4gYWN0aW9ucyBhcmUgcmVnZW5lcmF0ZWQ6XHJcbi8vIC0gdGhlIGltcG9ydCBsaXN0XHJcbi8vIC0gdGhlIGNvZGUgYmV0d2VlbiBCRUdJTiBVU0VSIENPREUgYW5kIEVORCBVU0VSIENPREVcclxuLy8gLSB0aGUgY29kZSBiZXR3ZWVuIEJFR0lOIEVYVFJBIENPREUgYW5kIEVORCBFWFRSQSBDT0RFXHJcbi8vIE90aGVyIGNvZGUgeW91IHdyaXRlIHdpbGwgYmUgbG9zdCB0aGUgbmV4dCB0aW1lIHlvdSBkZXBsb3kgdGhlIHByb2plY3QuXHJcbmltcG9ydCB7IEJpZyB9IGZyb20gXCJiaWcuanNcIjtcclxuXHJcbi8vIEJFR0lOIEVYVFJBIENPREVcclxuLy8gRU5EIEVYVFJBIENPREVcclxuXHJcbi8qKlxyXG4gKiBTaG93cyBkZWZhdWx0IHByb2dyZXNzIGJhclxyXG4gKiBAcGFyYW0ge3N0cmluZ30gbWVzc2FnZSAtIFRoZSB0ZXh0IHRvIHNob3cgd2hpbGUgbG9hZGluZy5cclxuICogQHBhcmFtIHtib29sZWFufSBibG9ja2luZyAtIEJsb2NrIHRoZSB1c2VyIGludGVyZmFjZSBpbW1lZGlhdGVseS5cclxuICogQHJldHVybnMge1Byb21pc2UuPEJpZz59XHJcbiAqL1xyXG5leHBvcnQgYXN5bmMgZnVuY3Rpb24gU2hvd1Byb2dyZXNzKG1lc3NhZ2UsIGJsb2NraW5nKSB7XHJcblx0Ly8gQkVHSU4gVVNFUiBDT0RFXHJcbiAgICBjb25zdCBpZCA9IG14LnVpLnNob3dQcm9ncmVzcyhtZXNzYWdlLCBibG9ja2luZyk7XHJcbiAgICBpZiAoaWQgIT09IHVuZGVmaW5lZCkge1xyXG4gICAgICAgIHJldHVybiBQcm9taXNlLnJlc29sdmUobmV3IEJpZyhpZCkpO1xyXG4gICAgfVxyXG4gICAgcmV0dXJuIFByb21pc2UucmVqZWN0KG5ldyBFcnJvcihcIkNvdWxkIG5vdCBvcGVuIHRoZSBsb2FkaW5nIGRpYWxvZ1wiKSk7XHJcblx0Ly8gRU5EIFVTRVIgQ09ERVxyXG59XHJcbiIsIm1vZHVsZS5leHBvcnRzID0gX19XRUJQQUNLX0VYVEVSTkFMX01PRFVMRV9iaWdfanNfXzsiLCIvKiBlbXB0eSAqLyIsIi8vIFRoZSBtb2R1bGUgY2FjaGVcbnZhciBfX3dlYnBhY2tfbW9kdWxlX2NhY2hlX18gPSB7fTtcblxuLy8gVGhlIHJlcXVpcmUgZnVuY3Rpb25cbmZ1bmN0aW9uIF9fd2VicGFja19yZXF1aXJlX18obW9kdWxlSWQpIHtcblx0Ly8gQ2hlY2sgaWYgbW9kdWxlIGlzIGluIGNhY2hlXG5cdHZhciBjYWNoZWRNb2R1bGUgPSBfX3dlYnBhY2tfbW9kdWxlX2NhY2hlX19bbW9kdWxlSWRdO1xuXHRpZiAoY2FjaGVkTW9kdWxlICE9PSB1bmRlZmluZWQpIHtcblx0XHRyZXR1cm4gY2FjaGVkTW9kdWxlLmV4cG9ydHM7XG5cdH1cblx0Ly8gQ3JlYXRlIGEgbmV3IG1vZHVsZSAoYW5kIHB1dCBpdCBpbnRvIHRoZSBjYWNoZSlcblx0dmFyIG1vZHVsZSA9IF9fd2VicGFja19tb2R1bGVfY2FjaGVfX1ttb2R1bGVJZF0gPSB7XG5cdFx0Ly8gbm8gbW9kdWxlLmlkIG5lZWRlZFxuXHRcdC8vIG5vIG1vZHVsZS5sb2FkZWQgbmVlZGVkXG5cdFx0ZXhwb3J0czoge31cblx0fTtcblxuXHQvLyBFeGVjdXRlIHRoZSBtb2R1bGUgZnVuY3Rpb25cblx0X193ZWJwYWNrX21vZHVsZXNfX1ttb2R1bGVJZF0obW9kdWxlLCBtb2R1bGUuZXhwb3J0cywgX193ZWJwYWNrX3JlcXVpcmVfXyk7XG5cblx0Ly8gUmV0dXJuIHRoZSBleHBvcnRzIG9mIHRoZSBtb2R1bGVcblx0cmV0dXJuIG1vZHVsZS5leHBvcnRzO1xufVxuXG4iLCIvLyBnZXREZWZhdWx0RXhwb3J0IGZ1bmN0aW9uIGZvciBjb21wYXRpYmlsaXR5IHdpdGggbm9uLWhhcm1vbnkgbW9kdWxlc1xuX193ZWJwYWNrX3JlcXVpcmVfXy5uID0gKG1vZHVsZSkgPT4ge1xuXHR2YXIgZ2V0dGVyID0gbW9kdWxlICYmIG1vZHVsZS5fX2VzTW9kdWxlID9cblx0XHQoKSA9PiAobW9kdWxlWydkZWZhdWx0J10pIDpcblx0XHQoKSA9PiAobW9kdWxlKTtcblx0X193ZWJwYWNrX3JlcXVpcmVfXy5kKGdldHRlciwgeyBhOiBnZXR0ZXIgfSk7XG5cdHJldHVybiBnZXR0ZXI7XG59OyIsIi8vIGRlZmluZSBnZXR0ZXIgZnVuY3Rpb25zIGZvciBoYXJtb255IGV4cG9ydHNcbl9fd2VicGFja19yZXF1aXJlX18uZCA9IChleHBvcnRzLCBkZWZpbml0aW9uKSA9PiB7XG5cdGZvcih2YXIga2V5IGluIGRlZmluaXRpb24pIHtcblx0XHRpZihfX3dlYnBhY2tfcmVxdWlyZV9fLm8oZGVmaW5pdGlvbiwga2V5KSAmJiAhX193ZWJwYWNrX3JlcXVpcmVfXy5vKGV4cG9ydHMsIGtleSkpIHtcblx0XHRcdE9iamVjdC5kZWZpbmVQcm9wZXJ0eShleHBvcnRzLCBrZXksIHsgZW51bWVyYWJsZTogdHJ1ZSwgZ2V0OiBkZWZpbml0aW9uW2tleV0gfSk7XG5cdFx0fVxuXHR9XG59OyIsIl9fd2VicGFja19yZXF1aXJlX18ubyA9IChvYmosIHByb3ApID0+IChPYmplY3QucHJvdG90eXBlLmhhc093blByb3BlcnR5LmNhbGwob2JqLCBwcm9wKSkiLCIvLyBkZWZpbmUgX19lc01vZHVsZSBvbiBleHBvcnRzXG5fX3dlYnBhY2tfcmVxdWlyZV9fLnIgPSAoZXhwb3J0cykgPT4ge1xuXHRpZih0eXBlb2YgU3ltYm9sICE9PSAndW5kZWZpbmVkJyAmJiBTeW1ib2wudG9TdHJpbmdUYWcpIHtcblx0XHRPYmplY3QuZGVmaW5lUHJvcGVydHkoZXhwb3J0cywgU3ltYm9sLnRvU3RyaW5nVGFnLCB7IHZhbHVlOiAnTW9kdWxlJyB9KTtcblx0fVxuXHRPYmplY3QuZGVmaW5lUHJvcGVydHkoZXhwb3J0cywgJ19fZXNNb2R1bGUnLCB7IHZhbHVlOiB0cnVlIH0pO1xufTsiLCJleHBvcnQgY29uc3QgTmFub2Zsb3dDb21tb25zJFNob3dQcm9ncmVzcyA9IGFzeW5jICgpID0+IChhd2FpdCBpbXBvcnQoXCJFOi9xdWl6YXBwLW14LWNvdXJzZS1tYXN0ZXIvamF2YXNjcmlwdHNvdXJjZS9uYW5vZmxvd2NvbW1vbnMvYWN0aW9ucy9TaG93UHJvZ3Jlc3NcIikpLlNob3dQcm9ncmVzcztcbmV4cG9ydCBjb25zdCBOYW5vZmxvd0NvbW1vbnMkSGlkZVByb2dyZXNzID0gYXN5bmMgKCkgPT4gKGF3YWl0IGltcG9ydChcIkU6L3F1aXphcHAtbXgtY291cnNlLW1hc3Rlci9qYXZhc2NyaXB0c291cmNlL25hbm9mbG93Y29tbW9ucy9hY3Rpb25zL0hpZGVQcm9ncmVzc1wiKSkuSGlkZVByb2dyZXNzO1xuZXhwb3J0IGNvbnN0IEJ1aWxkZXIkSlNfRml4X09uUXVlc3Rpb25DaGFuZ2UgPSBhc3luYyAoKSA9PiAoYXdhaXQgaW1wb3J0KFwiRTovcXVpemFwcC1teC1jb3Vyc2UtbWFzdGVyL2phdmFzY3JpcHRzb3VyY2UvYnVpbGRlci9hY3Rpb25zL0pTX0ZpeF9PblF1ZXN0aW9uQ2hhbmdlXCIpKS5KU19GaXhfT25RdWVzdGlvbkNoYW5nZTtcbmV4cG9ydCBjb25zdCBCdWlsZGVyJEpTX0ZpeF9PblF1ZXN0aW9uQm9keUNoYW5nZSA9IGFzeW5jICgpID0+IChhd2FpdCBpbXBvcnQoXCJFOi9xdWl6YXBwLW14LWNvdXJzZS1tYXN0ZXIvamF2YXNjcmlwdHNvdXJjZS9idWlsZGVyL2FjdGlvbnMvSlNfRml4X09uUXVlc3Rpb25Cb2R5Q2hhbmdlXCIpKS5KU19GaXhfT25RdWVzdGlvbkJvZHlDaGFuZ2U7XG4iXSwibmFtZXMiOlsiQmlnIiwiSlNfRml4X09uUXVlc3Rpb25Cb2R5Q2hhbmdlIiwicXVlc3Rpb24iLCJpc1dyYXBwZWQiLCJzdHJIVE1MIiwic3RhcnRzV2l0aCIsImVuZHNXaXRoIiwid3JhcCIsInBsYWNlQ2FyZXRBdEVuZCIsImVsIiwiZm9jdXMiLCJ3aW5kb3ciLCJnZXRTZWxlY3Rpb24iLCJkb2N1bWVudCIsImNyZWF0ZVJhbmdlIiwicmFuZ2UiLCJzZWxlY3ROb2RlQ29udGVudHMiLCJjb2xsYXBzZSIsInNlbCIsInJlbW92ZUFsbFJhbmdlcyIsImFkZFJhbmdlIiwiYm9keSIsImNyZWF0ZVRleHRSYW5nZSIsInRleHRSYW5nZSIsIm1vdmVUb0VsZW1lbnRUZXh0Iiwic2VsZWN0IiwicXVlc3Rpb25Cb2R5IiwiZ2V0IiwidGV4dEVkaXRvciIsImdldEVsZW1lbnRzQnlDbGFzc05hbWUiLCJ3cmFwcGVkIiwiaW5uZXJIVE1MIiwiSlNfRml4X09uUXVlc3Rpb25DaGFuZ2UiLCJIaWRlUHJvZ3Jlc3MiLCJpZGVudGlmaWVyIiwiUHJvbWlzZSIsInJlamVjdCIsIkVycm9yIiwibXgiLCJ1aSIsImhpZGVQcm9ncmVzcyIsIk51bWJlciIsInJlc29sdmUiLCJTaG93UHJvZ3Jlc3MiLCJtZXNzYWdlIiwiYmxvY2tpbmciLCJpZCIsInNob3dQcm9ncmVzcyIsInVuZGVmaW5lZCIsIk5hbm9mbG93Q29tbW9ucyRTaG93UHJvZ3Jlc3MiLCJOYW5vZmxvd0NvbW1vbnMkSGlkZVByb2dyZXNzIiwiQnVpbGRlciRKU19GaXhfT25RdWVzdGlvbkNoYW5nZSIsIkJ1aWxkZXIkSlNfRml4X09uUXVlc3Rpb25Cb2R5Q2hhbmdlIl0sInNvdXJjZVJvb3QiOiIifQ==